name: DiceEaster
version: 0.1
description: DiceEaster
author: Ste3et_C0st
website: http://dicecraft.de

main: me.Ste3et_C0st.DiceEaster.main
commands: 
  easter:
    description:  DiceEaster Egg Command
    usage:  /<command>